# Site settings
name: Arshiya Qureshi
title: Arshiya Qureshi | Full Stack Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://qu-arshiya.github.io/
baseurl: ''
email: qu.arshiya@gmail.com
cover: https://qu-arshiya.github.io/img/og.png
logo: https://qu-arshiya.github.io/img/emojis/technologist.png
resume: https://qu-arshiya.github.io/resume.pdf
social:
  - title: email
    url: mailto:qu.arshiya@gmail.com
  - title: twitter
    url: https://twitter.com/qu.arshiya
  - title: github
    url: https://github.com/qu-arshiya
  - title: linkedin
    url: https://www.linkedin.com/in/qu-arshiya

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
